clc;
clear all;
close all;
A = imread('sun.jpg');
B = rgb2gray(A);
gamma = 1.0;
C = double(A).^gamma;
subplot(2,4,1);
imshow(A);
title('Original Image');
subplot(2,4,2);
imshow(uint8(C));
title('Enhanced Image(gamma = 1.0)');
gamma = 1.1;
D = double(A).^gamma;
subplot(2,4,3);
imshow(uint8(D));
title('Enhanced Image(gamma = 1.1)');
gamma = 1.2;
E = double(A).^gamma;
subplot(2,4,4);
imshow(uint8(E));
title('Enhanced Image(gamma = 1.2)');
gamma = 1.3;
F = double(A).^gamma;
subplot(2,4,5);
imshow(uint8(F));
title('Enhanced Image(gamma = 1.3)');
gamma = 0.9;
G = double(A).^gamma;
subplot(2,4,6);
imshow(uint8(G));
title('Enhanced Image(gamma = 0.9)');
gamma = 0.8;
H = double(A).^gamma;
subplot(2,4,7);
imshow(uint8(H));
title('Enhanced Image(gamma = 0.8)');
gamma = 0.7;
I = double(A).^gamma;
subplot(2,4,8);
imshow(uint8(I));
title('Enhanced Image(gamma = 0.7)');
gtext('Udit Maherwal 17EGJCS171');
