clc;
clear all;
close all;
A = imread('sun.jpg');
subplot(2,3,1);
imshow(A);
title('Original Image');
subplot(2,3,2);
B = imresize(A, [32, 32]);
imshow(B);
title('Modified Image');
subplot(2,3,3);
C = imrotate(A,180);
imshow(C);
title('Rotate Image');
subplot(2,3,4);
D = imcrop(A);
imshow(D);
title('Crop Image');
gtext('Udit Maherwal 17EGJCS171');
